// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

// Explicitly load .env.local file first
const envPath = resolve(process.cwd(), ".env.local");
const result = config({ path: envPath });

// Get DATABASE_URL from process.env after loading
// Remove quotes if present (dotenv sometimes includes them)
let databaseUrl = process.env.DATABASE_URL;
if (databaseUrl) {
  // Remove surrounding quotes if present
  databaseUrl = databaseUrl.replace(/^["']|["']$/g, "");
}

if (!databaseUrl) {
  throw new Error(
    `DATABASE_URL is required. Please set it in your .env.local file. Loaded from: ${envPath}`
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
